name: theventapp
description: "A platform where users post their feelings and thoughts anonymously."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.8.4

  # Navigation
  go_router: ^14.6.2

  # Image Picker
  image_picker: ^1.1.2

  # Storing session locally
  shared_preferences: ^2.3.3

  # URL Launcher
  url_launcher: ^6.3.0  # ← Moved here

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"